#!/bin/sh
#?
#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org
START=99
start() {
        sleep 5   # make sure boot process is done, no more console msgs
        . /etc/profile
        cd /opt/prodmon/
        python3 prodmon/plc_collect/main.py &
        echo "Collect Started"
}

stop()  {
   pid=`ps -ef | grep '[p]ython3 prodmon/plc_collect/main.py' | awk '{ print $1 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Collect Stopped"
}

case "$1" in
  start)
   start
   ;;
 stop)
   stop
   ;;
  restart)
   stop
   start
   ;;
  *)
    echo "Usage: /etc/init.d/collect {start|stop|restart}"
    exit 1
esac
exit 0
