#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

USE_PROCD=1

#START=99

#start() {
#        ubus -t 60 wait_for network.interface network.interface.loopback
#        sleep 5   # make sure boot process is done, no more console msgs
#        echo "Collect Started"
#        cd /opt/prodmon/
#        /usr/bin/python3 prodmon/plc_collect/main.py &
#}

#!/bin/sh /etc/rc.common


START=95
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command "cd /opt/prodmon;/usr/bin/python3 prodmon/plc_collect/main.py"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}