#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

USE_PROCD=1

START=95
STOP=01

start_service() {
    procd_open_instance prodmon-post
    procd_set_param command bin/sh -c "cd /opt/prodmon; /usr/bin/python3 prodmon/db_post/main.py"

    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}