#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99

start() {
        ubus -t 60 wait_for network.interface network.interface.loopback
        sleep 5   # make sure boot process is done, no more console msgs
        echo "Collect Started"
        cd /opt/prodmon/
        /usr/bin/python3 prodmon/db_post/main.py &
}

