devices:

  - driver: pylogix               # type = pylogix | modbus
    name: '10R80 OP110 1511'
    ip: 192.168.1.50               # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    frequency: 1
    tags:
      - type: ping
        name: '10R80 OP110 1501'
        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 300
        table: prodmon_ping          # database table to write to

      - type: counter
        tag: 'Program:MainProgram.ProdCount.acc'
        scale: 2
        part_number: '50-9341'
        machine: 1511                 # written to machine column in db
        table: GFxPRoduction          # database table to write tominimum_cycle: .5

  - driver: pylogix               # type = pylogix | modbus
    name: '10R80 OP100 1530'
    ip: 192.168.1.170               # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    frequency: 1
    tags:
      - type: ping
        name: '10R80 OP100 1530'
        tag: 'Program:MainProgram.ProdCount.acc'
        frequency: 300
        table: prodmon_ping          # database table to write to

      - type: counter
        tag: 'Program:MainProgram.ProdCount.acc'
        scale: 2
        part_number: '50-9341'
        machine: 1530                 # written to machine column in db
        table: GFxPRoduction          # database table to write tominimum_cycle: .5

#      - type: counter
#        tag: 'Program:MainProgram.ProdCountReject.acc'
#        scale: 2
#        part_number: '50-9341'
#        machine: 1530REJ              # written to machine column in db
#        table: GFxPRoduction          # database table to write tominimum_cycle: .5
