minimum_cycle: .5

tags:
  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.20    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCount1529.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1529                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.20    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCount776.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 776                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.30    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCount1543.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1543                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.30    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCount1824.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1824                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram_Overhead.ProdCount.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 2
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1805                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.9     # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram_Overhead.ProdCount.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 2
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1804                 # written to machine column in db
