sqldir: ./tempSQL/
minimum_cycle: .5

tags:
  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 10.4.42.135     # processor_ip is the controller's ip address
    processor_slot: 3             # processor_slot is the controller's slot
    tag: Program:Production.ProdCount1.ACC    # tag is the PLC tag to read
    Part_Number: '50-5081'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1617                 # written to machine colum in db
    # used internally to track the readings
    nextread: 0     # timestamp of the next reading
    lastcount: 0    # last counter value
    lastread: 0     # timestamp of the last read

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 10.4.42.135     # processor_ip is the controller's ip address
    processor_slot: 3             # processor_slot is the controller's slot
    tag: Program:Production.ProdCount2.ACC    # tag is the PLC tag to read
    Part_Number: '50-4865'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1617                 # written to machine colum in db
    # used internally to track the readings
    nextread: 0     # timestamp of the next reading
    lastcount: 0    # last counter value
    lastread: 0     # timestamp of the last read
