devices:

  - driver: pylogix               # type = pylogix | modbus
    name: 'GFx Gauge'
    ip: 192.168.1.1               # processor_ip is the controller's ip address
    processor_slot: 3             # processor_slot is the controller's slot
    frequency: .4
    tags:
      - type: ping
        name: 'GFx Auto Gauge'
        tag: 'Program:Production.ProdCount1.ACC'
        frequency: 300
        table: prodmon_ping          # database table to write to

      - type: counter
        tag: 'Program:Production.ProdCount1.ACC'
        scale: 1
        part_number: '50-5081'
        machine: 1617                 # written to machine column in db
        table: GFxPRoduction          # database table to write to

      - type: counter
        tag: 'Program:Production.ProdCount2.ACC'    # tag is the PLC tag to read
        scale: 1
        part_number: '50-4865'
        machine: 1617                 # written to machine column in db
        table: GFxPRoduction          # database table to write to
