minimum_cycle: .5
tags:
  - type: pylogix                               # type = pylogix | modbus
    processor_ip: 192.168.100.50                # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:Cell_5.ProdCount1.acc                         # tag is the PLC tag to read
    Part_Number: '10R140'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1706                 # written to machine column in db
    # used internally to track the readings
    nextread: 0     # timestamp of the next reading
    lastcount: 0    # last counter value
    lastread: 0     # timestamp of the last read

  - type: pylogix                               # type = pylogix | modbus
    processor_ip: 192.168.100.50                # processor_ip is the controlle$
    processor_slot: 0
    tag: Program:Cell_5.ProdCount2.acc   # tag is the PLC tag to read
    Part_Number: 'AB1V Input'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1706                 # written to machine column in db
    # used internally to track the readings
    nextread: 0     # timestamp of the next reading
    lastcount: 0    # last counter value
    lastread: 0     # timestamp of the last read



