minimum_cycle: .5

tags:
  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.150              # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCount0455.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 1
    frequency: 1                            # how often to try to read the tag in seconds
    table: GFxPRoduction                    # database table to write to
    Machine: 1806                           # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.150              # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCountReject0455.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 1
    frequency: 1                            # how often to try to read the tag in seconds
    table: GFxPRoduction                    # database table to write to
    Machine: 1806REJ                        # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.150              # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCount9341.acc  # tag is the PLC tag to read
    Part_Number: '50-9341'
    Scale: 1
    frequency: 1                            # how often to try to read the tag in seconds
    table: GFxPRoduction                    # database table to write to
    Machine: 1806                           # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.150             # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProdCountReject9341.acc  # tag is the PLC tag to read
    Part_Number: '50-9341'
    Scale: 1
    frequency: 1                            # how often to try to read the tag in seconds
    table: GFxPRoduction                    # database table to write to
    Machine: 1806REJ                        # written to machine column in db
