minimum_cycle: .5

tags:
  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.60    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProductionCount.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 2
    frequency: 1                  # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1808                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.70    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProductionCount.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 2
    frequency: 1                  # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1810                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.80    # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProductionCount.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 2
    frequency: 1                  # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1815                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.1.100   # processor_ip is the controller's ip address
    processor_slot: 0
    tag: Program:MainProgram.ProductionCount.acc  # tag is the PLC tag to read
    Part_Number: '50-0455'
    Scale: 2
    frequency: 1                  # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 1812                 # written to machine column in db
