minimum_cycle: .5

tags:
  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.1   # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:MainProgram.ProdCountLine.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 728                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.1   # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:MainProgram.ProdCountOverflow.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 728O                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.1   # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:MainProgram.ProdCountReject.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 728R                 # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.46  # processor_ip is the controller's ip address
    processor_slot: 12            # processor_slot is the controller's slot
    tag: 'Program:OKUMA_1.ProdCount.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 647                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.46  # processor_ip is the controller's ip address
    processor_slot: 12            # processor_slot is the controller's slot
    tag: 'Program:OKUMA_2.ProdCount.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 648                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.46  # processor_ip is the controller's ip address
    processor_slot: 12            # processor_slot is the controller's slot
    tag: 'Program:OKUMA_3.ProdCount.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 649                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.46  # processor_ip is the controller's ip address
    processor_slot: 12            # processor_slot is the controller's slot
    tag: 'Program:OKUMA_4.ProdCount.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 646                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.46  # processor_ip is the controller's ip address
    processor_slot: 12            # processor_slot is the controller's slot
    tag: 'Program:OKUMA_5.ProdCount.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 645                  # written to machine column in db

  - type: pylogix                 # type = pylogix | modbus
    processor_ip: 192.168.100.46  # processor_ip is the controller's ip address
    processor_slot: 12            # processor_slot is the controller's slot
    tag: 'Program:OKUMA_6.ProdCount.ACC'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 644                  # written to machine column in db

  - type: modbus                  # type = pylogix | modbus
    processor_ip: 10.4.42.169     # processor_ip is the controller's ip address
    register: 16                  # modbus register to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 650L                 # written to machine column in db

  - type: modbus                  # type = pylogix | modbus
    processor_ip: 10.4.42.169     # processor_ip is the controller's ip address
    register: 18                  # modbus register to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 650R                  # written to machine column in db

