minimum_cycle: .5

tags:
  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:Deburr_Cell.CountPart31.acc'    # tag is the PLC tag to read
    Part_Number: '50-3050'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 769                  # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:Deburr_Cell.CountPart32.acc'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 769                  # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:Deburr_Cell.CountPart33.acc'    # tag is the PLC tag to read
    Part_Number: '50-5710'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 769                  # written to machine column in db


  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:Broach_Cell.CountPart21.acc'    # tag is the PLC tag to read
    Part_Number: '50-3050'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 770                  # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:Broach_Cell.CountPart22.acc'    # tag is the PLC tag to read
    Part_Number: '50-1467'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 770                  # written to machine column in db

  - type: pylogix                           # type = pylogix | modbus
    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    tag: 'Program:Broach_Cell.CountPart23.acc'    # tag is the PLC tag to read
    Part_Number: '50-5710'
    Scale: 1
    frequency: .5                 # how often to try to read the tag in seconds
    table: GFxPRoduction          # database table to write to
    Machine: 770                  # written to machine column in db

##### begin new configuration
#  - type: pylogix                           # type = pylogix | modbus
#    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
#    processor_slot: 0             # processor_slot is the controller's slot
#    tag: 'Program:Deburr_Cell.CountPart31.acc'    # tag is the PLC tag to read
##    Part_Number: '50-3050'
#    Scale: 1
#    frequency: .5                 # how often to try to read the tag in seconds
#    table: prodmon_3050_Slurry    # database table to write to
#    Machine: 769                  # written to machine column in db
#
#  - type: pylogix                           # type = pylogix | modbus
#    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
#    processor_slot: 0             # processor_slot is the controller's slot
#    tag: 'Program:Deburr_Cell.CountPart32.acc'    # tag is the PLC tag to read
##    Part_Number: '50-1467'
#    Scale: 1
#    frequency: .5                 # how often to try to read the tag in seconds
#    table: prodmon_1467_Slurry    # database table to write to
#    Machine: 769                  # written to machine column in db
#
#  - type: pylogix                           # type = pylogix | modbus
#    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
#    processor_slot: 0             # processor_slot is the controller's slot
#    tag: 'Program:Deburr_Cell.CountPart33.acc'    # tag is the PLC tag to read
##    Part_Number: '50-5710'
#    Scale: 1
#    frequency: .5                 # how often to try to read the tag in seconds
#    table: prodmon_5710_Slurry    # database table to write to
#    Machine: 769                  # written to machine column in db
#
#  - type: pylogix                           # type = pylogix | modbus
#    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
#    processor_slot: 0             # processor_slot is the controller's slot
#    tag: 'Program:Broach_Cell.CountPart21.acc'    # tag is the PLC tag to read
##    Part_Number: '50-3050'
#    Scale: 1
#    frequency: .5                 # how often to try to read the tag in seconds
#    table: prodmon_3050_Harden    # database table to write to
#    Machine: 770                  # written to machine column in db
#
#  - type: pylogix                           # type = pylogix | modbus
#    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
#    processor_slot: 0             # processor_slot is the controller's slot
#    tag: 'Program:Broach_Cell.CountPart22.acc'    # tag is the PLC tag to read
##    Part_Number: '50-1467'
#    Scale: 1
#    frequency: .5                 # how often to try to read the tag in seconds
#    table: prodmon_1467_Harden    # database table to write to
#    Machine: 770                  # written to machine column in db
#
#  - type: pylogix                           # type = pylogix | modbus
#    processor_ip: 192.168.1.1     # processor_ip is the controller's ip address
#    processor_slot: 0             # processor_slot is the controller's slot
#    tag: 'Program:Broach_Cell.CountPart23.acc'    # tag is the PLC tag to read
##    Part_Number: '50-5710'
#    Scale: 1
#    frequency: .5                 # how often to try to read the tag in seconds
#    table: prodmon_5710_Harden    # database table to write to
#    Machine: 770                  # written to machine column in db
