devices:

  - driver: pylogix               # type = pylogix | modbus
    name: '936 6L Auto Gauge'
    ip: 10.4.42.136               # processor_ip is the controller's ip address
    processor_slot: 0             # processor_slot is the controller's slot
    frequency: 1
    tags:
      - type: ping
        name: '936 6L Auto Gauge'
        tag: 'Program:Deburr_Cell.CountPart31.acc'
        frequency: 600
        table: prodmon_ping      # database table to write to

      - type: counter
        tag: 'ProdCountX16.acc'
        scale: 1
        part_number: '50-6729'
        machine: 936                  # written to machine column in db
        table: GFxPRoduction          # database table to write to

      - type: counter
        tag: 'ProdCountX15.acc'
        scale: 1
        part_number: '50-6686'
        machine: 936                  # written to machine column in db
        table: GFxPRoduction          # database table to write to

      - type: counter
        tag: 'ProdCountX14.acc'
        scale: 1
        part_number: '50-4900'
        machine: 936                  # written to machine column in db
        table: GFxPRoduction          # database table to write to

